name: Print Node.js Version

on:
  push:
    branches:
      - main

jobs:
  print_version:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print Node.js version
        run: node -v
